# Change these first
owner: edgardoramosroque # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portal UNA
    url: https://www.una.ac.cr/
  - name: Carreras UNA
    url: https://www.carreras.una.ac.cr/    
  - name: Calendario Universitario  
    url: https://www.calendario.una.ac.cr/
  - name: Portal Directorio
    url: https://www.directorio.una.ac.cr/
  - name: Portal UNACOMUNICA
    url: https://www.unacomunica.una.ac.cr/    
  - name: Portal Transparencia
    url: https://www.transparencia.una.ac.cr/    
  - name: Portal Preguntas Frecuentes
    url: https://www.preguntasfrecuentes.una.ac.cr/
  - name: Portal COVID19
    url: https://www.covid19.una.ac.cr/
  - name: Portal Documentos
    url: https://www.documentos.una.ac.cr/
  - name: Portal Repositorio
    url: https://www.repositorio.una.ac.cr/
  - name: Portal Revistas Universitarias
    url: https://www.revistas.una.ac.cr/
  - name: Portal RedAcademica
    url: https://redacademica.una.ac.cr/
  - name: Portal Rectoria
    url: https://www.rectoria.una.ac.cr/
  - name: Portal Registro
    url: https://www.registro.una.ac.cr/
  - name: Aula Virtual - Institucional
    url: https://www.aulavirtual.una.ac.cr/
  - name: Portal Bibliotecas
    url: https://www.siduna.una.ac.cr/
  - name: Portal Vicerrectoria Vida Estudiantil
    url: https://www.vidaestudiantil.una.ac.cr/
  - name: Portal Vicerrectoria Administracion
    url: https://www.vadm.una.ac.cr/
  - name: Portal Vicerrectoria Extension
    url: https://www.extension.una.ac.cr/
  - name: Portal Vicerrectoria Docencia
    url: https://www.docencia.una.ac.cr/
  - name: Portal Proveeduria
    url: https://www.proveeduria.una.ac.cr/
  - name: Portal Facultad Filosofia
    url: https://www.facultadfilosofia.una.ac.cr/
  - name: Portal Facultad de Tierra y Mar
    url: http://www.tierraymar.una.ac.cr/
  - name: Portal Facultad de Ciencias Social
    url: https://www.cienciassociales.una.ac.cr/
  - name: Portal Facultad de Ciencias Exactas y Naturales
    url: https://www.exactasynaturales.una.ac.cr/
  - name: Portal Facultad de Ciencias de la Salud
    url: https://www.fcsalud.una.ac.cr/    
  - name: Portal Estudios Generales
    url: https://www.ceg.una.ac.cr/
  - name: Portal CIDE
    url: https://www.cide.una.ac.cr/
  - name: Portal CIDEA
    url: http://www.cidea.una.ac.cr/
  - name: Live CIDEA
    url: https://live.radiocidea.una.ac.cr
    
assignees:
  - edgardoramosroque
  
status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.una.ac.cr
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/EdgardoRamosRoque/status/7b9f15eb4aae9902387fef6183fb264e64fb3b89/Logo-UNA.svg
  name: Estado de URL Universidad Nacional
  introTitle: "P&aacute;gina de estado de los URL de la Universidad Nacional de Costa Rica, (https://www.una.ac.cr/)"
  introMessage: Mediante este sitio, verificamos el estado de los portales Universitarios.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: UNA
      href: https://www.una.ac.cr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
