# Change these first
owner: edgardoramosroque # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portal UNA
    url: https://www.una.ac.cr
  - name: Aula Virtual - Institucional
    url: https://www.aulavirtual.una.ac.cr/login/index.php
  - name: Portal Bibliotecas
    url: https://www.siduna.una.ac.cr/
  - name: Portal Directorio
    url: https://www.directorio.una.ac.cr/
  - name: Calendario Universitario
    url: https://www.calendario.una.ac.cr
  - name: Portal Preguntas Frecuentes
    url: https://www.preguntasfrecuentes.una.ac.cr
  - name: Portal Documentos
    url: https://www.documentos.una.ac.cr
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    
assignees:
  - edgardoramosroque
  
status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado de URL Universidad Nacional
  introTitle: "P&aacute;gina de estado de los URL de la Universidad Nacional de Costa Rica, (https://www.una.ac.cr/) basado en una herramienta OpenSource **Upptime** 
  , hospedada y soportada por GitHub."
  introMessage: Mediante este sitio, verificamos el estado de los portales Universitarios.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  url: "URL"
  status: "Estado"
  history: "Historia"
  responseTime: "Tiempo de respuesta"
  uptime: "Tiempo activo"
  up: "游릴 Arriba"
  degraded: "游릳 Degradada"
  down: "游린 Abajo"
  responseTimeGraphAlt: "Response time graph"
  ms: "ms"
  responseTime: "Response time"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  uptime: "All-time uptime"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  liveStatus: "Estado de Sitios"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "游릴 Todos los sistemas operacionales"
  degradedPerformance: "游릳 Desempe&ntilde;o degradado"
  completeOutage: "游린 Interrupci&otilde;n completa"
  partialOutage: "游릲 Interrupci&oacute;n parcial"
